# Generated by Django 5.0.2 on 2024-03-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('picture1', models.ImageField(upload_to='media')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='media')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='media')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfolder.position')),
            ],
        ),
    ]
