# Generated by Django 5.0.2 on 2024-03-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0002_position_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture2',
            field=models.URLField(blank=True, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture3',
            field=models.URLField(blank=True, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture4',
            field=models.URLField(blank=True, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture5',
            field=models.URLField(blank=True, null=True, verbose_name='media'),
        ),
    ]
