# Generated by Django 5.0.2 on 2024-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0003_alter_team_picture2_alter_team_picture3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('picture1', models.ImageField(upload_to='media')),
            ],
        ),
    ]
