# Generated by Django 5.0.2 on 2024-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gmail', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
