# Generated by Django 5.0.2 on 2024-03-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=50)),
            ],
        ),
    ]
